name: Go build/release
on:
  push:
    branches: [ "main" ]
    tags:
      - "v*.*.*"
jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setup environment
      uses: actions/setup-go@v4
      with:
        go-version: 1.22
    - name: build
      run: |
        CGO_ENABLED=0
        GOOS=linux GOARCH=amd64 go build -o purelymail-${{github.ref_name}}-linux-amd64 -ldflags="-w -s"
        GOOS=darwin GOARCH=arm64 go build -o purelymail-${{github.ref_name}}-darwin-arm64 -ldflags="-w -s"
        GOOS=windows GOARCH=amd64 go build -o purelymail-${{github.ref_name}}-windows-amd64.exe -ldflags="-w -s"
    - name: release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          purelymail-${{github.ref_name}}-linux-amd64
          purelymail-${{github.ref_name}}-darwin-arm64
          purelymail-${{github.ref_name}}-windows-amd64.exe
